name: GCP Federation Test
on: [push]

permissions:
  contents: 'read'
  id-token: 'write' # REQUIRED for Federation

jobs:
  test-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_DEPLOYER_SA }}

      - name: 'List Buckets'
        run: gcloud storage ls
